/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gmssl_SDF */

#ifndef _Included_org_gmssl_SDF
#define _Included_org_gmssl_SDF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gmssl_SDF
 * Method:    getDeviceInfo
 * Signature: ()Lorg/gmssl/SDF/DeviceInfo;
 */
JNIEXPORT jobject JNICALL Java_org_gmssl_SDF_getDeviceInfo
  (JNIEnv *, jobject);

/*
 * Class:     org_gmssl_SDF
 * Method:    generateRandom
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_gmssl_SDF_generateRandom
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmssl_SDF
 * Method:    generateKeyPair_RSA
 * Signature: (ILorg/gmssl/SDF/RSArefPublicKey;Lorg/gmssl/SDF/RSArefPrivateKey;)I
 */
JNIEXPORT jobject JNICALL Java_org_gmssl_SDF_generateKeyPair_1RSA
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gmssl_SDF
 * Method:    generateKeyPair_ECC
 * Signature: (IILorg/gmssl/SDF/ECCrefPublicKey;Lorg/gmssl/SDF/ECCrefPrivateKey;)I
 */
JNIEXPORT jobject JNICALL Java_org_gmssl_SDF_generateKeyPair_1ECC
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
